holiday_bot_api_email: vkdeveloper2@gmail.com
holiday_bot_api_url: https://holidays.abstractapi.com/v1/
holiday_bot_api_key: 693d9c9d092245aeaa1487c9bad61348

open_weather_api_key: cfa728d052db0ef6f1300948ac003280
open_weather_api_url: https://api.openweathermap.org/data/2.5/weather